/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package voters;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import sqlcommands.SQLConnector;
import utilities.PopupWindows;

/**
 *
 * @author Christian
 */
public class PresidentForm extends javax.swing.JFrame {

    /**
     * Creates new form PresidentForm
     */
    private Connection conn;
    
    private void displayPresidents() {
        DefaultTableModel model = (DefaultTableModel) tblPres.getModel();
        model.setRowCount(0); // Clear existing rows

        try {
            String sql = "SELECT candidate_no, name, partylist FROM tbl_candidates WHERE position = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, "President");

            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                int candidateNo = rs.getInt("candidate_no");
                String name = rs.getString("name");
                String partylist = rs.getString("partylist");

                model.addRow(new Object[]{candidateNo, name, partylist});
            }
        } catch (SQLException e) {
            PopupWindows.errorMessage("Candidate Request Error - 0013", e.getMessage());
        }
    }
    
    private void setTextFields() {
        txtPresNo.setText(Variables.PresID);
        txtPresName.setText(Variables.PresName);
        txtPresPartylist.setText(Variables.PresPartylist);
    }
    
    private void tblPresRowClicked() {
        int selectedRow = tblPres.getSelectedRow();

        if (selectedRow >= 0) {
            // Get values from the table (for backup or validation)
            String presNo = tblPres.getValueAt(selectedRow, 0).toString();
            String presName = tblPres.getValueAt(selectedRow, 1).toString();
            String presPartylist = tblPres.getValueAt(selectedRow, 2).toString();

            // Set values to the Variables class
            Variables.PresID = presNo;
            Variables.PresName = presName;
            Variables.PresPartylist = presPartylist;

            // Now set the text fields using the variables from the Variables class
            setTextFields();
        }
    }

    public PresidentForm() {
        initComponents();
        
        conn = SQLConnector.connectToDB();
        
        displayPresidents();
        
        setTextFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPres = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPresNo = new javax.swing.JTextField();
        txtPresName = new javax.swing.JTextField();
        txtPresPartylist = new javax.swing.JTextField();
        btnPresNext = new javax.swing.JButton();
        lblPresError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setText("PRESIDENT");

        tblPres.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblPres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CANDIDATE NO.", "NAME", "PARTYLIST"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPres);
        if (tblPres.getColumnModel().getColumnCount() > 0) {
            tblPres.getColumnModel().getColumn(0).setMinWidth(120);
            tblPres.getColumnModel().getColumn(0).setPreferredWidth(120);
            tblPres.getColumnModel().getColumn(0).setMaxWidth(120);
            tblPres.getColumnModel().getColumn(2).setMinWidth(150);
            tblPres.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblPres.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setText("SELECTED CANDIDATE");

        jLabel3.setText("Candidate No.:");

        jLabel4.setText("Name:");

        jLabel5.setText("Partlist:");

        txtPresNo.setEditable(false);

        txtPresName.setEditable(false);

        txtPresPartylist.setEditable(false);

        btnPresNext.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnPresNext.setText("Next");
        btnPresNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresNextActionPerformed(evt);
            }
        });

        lblPresError.setFont(new java.awt.Font("Poppins", 2, 12)); // NOI18N
        lblPresError.setForeground(new java.awt.Color(247, 71, 71));
        lblPresError.setText("          ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPresPartylist, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(110, 110, 110)
                                        .addComponent(btnPresNext, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPresNo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPresName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblPresError)))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPresError))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPresNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPresName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPresPartylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPresNext))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPresNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresNextActionPerformed
        VicePresidentForm vp = new VicePresidentForm();
        
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPresNextActionPerformed

    private void tblPresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPresMouseClicked
        tblPresRowClicked();
    }//GEN-LAST:event_tblPresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresidentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresidentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresidentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresidentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PresidentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPresNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPresError;
    private javax.swing.JTable tblPres;
    private javax.swing.JTextField txtPresName;
    private javax.swing.JTextField txtPresNo;
    private javax.swing.JTextField txtPresPartylist;
    // End of variables declaration//GEN-END:variables
}
