/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package voters;

import javax.swing.table.DefaultTableModel;
import login.LoginForm;
import security.Blockchain;
import utilities.PopupWindows;

/**
 *
 * @author Christian
 */
public class Summary extends javax.swing.JFrame {

    /**
     * Creates new form Summarry
     */
    private void loadSummaryData() {
        DefaultTableModel modelPres = (DefaultTableModel) tblPres.getModel();
        DefaultTableModel modelVPres = (DefaultTableModel) tblVPres.getModel();
        DefaultTableModel modelSenators = (DefaultTableModel) tblSenators.getModel();

        // Clear existing rows in the tables
        modelPres.setRowCount(0);
        modelVPres.setRowCount(0);
        modelSenators.setRowCount(0);

        // Load the President data into tblPres
        if (!Variables.PresID.isEmpty() && !Variables.PresName.isEmpty()) {
            modelPres.addRow(new Object[]{Variables.PresID, Variables.PresName, Variables.PresPartylist});
        }

        // Load the Vice President data into tblVPres
        if (!Variables.VPresID.isEmpty() && !Variables.VPresName.isEmpty()) {
            modelVPres.addRow(new Object[]{Variables.VPresID, Variables.VPresName, Variables.VPresPartylist});
        }

        // Load the Selected Senators into tblSenators
        for (String senatorEntry : Variables.SelectedSenators) {
            String[] senatorData = senatorEntry.split("\\|");
            if (senatorData.length == 3) {
                modelSenators.addRow(new Object[]{senatorData[0], senatorData[1], senatorData[2]});
            }
        }
    }
    
    private void submitVote() {
        Blockchain.initializeChain(); // Initialize blockchain if not already

        StringBuilder voteData = new StringBuilder();

        voteData.append("President: ")
                .append(Variables.PresID).append("-")
                .append(Variables.PresName).append("-")
                .append(Variables.PresPartylist).append("\n");

        voteData.append("Vice President: ")
                .append(Variables.VPresID).append("-")
                .append(Variables.VPresName).append("-")
                .append(Variables.VPresPartylist).append("\n");

        voteData.append("Senators:\n");
        for (String senator : Variables.SelectedSenators) {
            voteData.append(senator).append("\n");
        }

        // Add to blockchain
        Blockchain.addVoteBlock(voteData.toString());

        // Optional: confirmation
        PopupWindows.dialogMessage("Vote Submitted", "Your vote has been recorded securely.");
    }


    public Summary() {
        initComponents();
        
        loadSummaryData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFinish = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSenators = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVPres = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPres = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnFinish1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFinish.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnFinish.setText("Confirm Vote!");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        tblSenators.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblSenators.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CANDIDATE NO.", "NAME", "PARTYLIST"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblSenators);

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel3.setText("SENATORS");

        tblVPres.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblVPres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CANDIDATE NO.", "NAME", "PARTYLIST"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVPres);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setText("VICE PRESIDENT");

        tblPres.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblPres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CANDIDATE NO.", "NAME", "PARTYLIST"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPres);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setText("PRESIDENT");

        btnFinish1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnFinish1.setText("Back");
        btnFinish1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinish1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFinish1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinish)
                    .addComponent(btnFinish1))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        submitVote();
        
        LoginForm login = new LoginForm();
        
        login.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnFinishActionPerformed

    private void btnFinish1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinish1ActionPerformed
        SenatorsForm senators = new SenatorsForm();
        
        senators.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFinish1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Summary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnFinish1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblPres;
    private javax.swing.JTable tblSenators;
    private javax.swing.JTable tblVPres;
    // End of variables declaration//GEN-END:variables
}
